# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
package:
  name: portefaix-distroless
  version: 0.1.0
  description: "Portefaix tools for CI/CD"
  target-architecture:
  - all
  copyright:
  - license: Apache-2.0
    paths:
    - "*"
  dependencies:
    runtime:

environment:
  contents:
    # keyring:
    # - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
    # - https://packages.wolfi.dev/os
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
    # - wolfi-baselayout # replaces alpine-baselayout-data
    - alpine-baselayout-data
    - ca-certificates-bundle
    - busybox
    - curl

pipeline:
# - uses: strip
- name: Install dependencies
  runs: |
    set -x
    ARCH=$(uname -m)
    case $ARCH in
      "x86_64") ARCH="amd64" ;;
      "aarch64") ARCH="arm64" ;;
    esac
    install -D entrypoint.sh ${{targets.destdir}}/usr/bin/entrypoint.sh
    install -D kubectl-${ARCH} ${{targets.destdir}}/usr/bin/kubectl
    install -D helm-${ARCH} ${{targets.destdir}}/usr/bin/helm
    install -D kustomize-${ARCH} ${{targets.destdir}}/usr/bin/kustomize
    install -D yq-${ARCH} ${{targets.destdir}}/usr/bin/yq
    install -D kubeval-${ARCH} ${{targets.destdir}}/usr/bin/kubeval
    install -D kubeconform-${ARCH} ${{targets.destdir}}/usr/bin/kubeconform
    install -D opa-${ARCH} ${{targets.destdir}}/usr/bin/opa
    install -D conftest-${ARCH} ${{targets.destdir}}/usr/bin/conftest
    install -D jb-${ARCH} ${{targets.destdir}}/usr/bin/jb
