# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
include: images/infra-tools/shell.yaml

contents:
  packages:
  - apk-tools
  - git
  - wolfi-keys

accounts:
  run-as: root
