# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

---
name: Image / Build

on: # yamllint disable-line rule:truthy
  pull_request:

jobs:
  build:
    name: Build OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Dependencies
      run: ./cicd/deps.sh

    - uses: sigstore/cosign-installer@main

    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        archs: x86_64,aarch64

    - uses: chainguard-images/actions/apko-build@main
      with:
        config: cicd/apko.yaml
        tag: portefaix-distroless:cicd-dev
        keyring-append: /work/melange.rsa.pub
        archs: x86_64,aarch64

    - name: load image for testing
      run: docker load -i output.tar

    - name: run structure tests
      uses: plexsystems/container-structure-test-action@v0.2.0
      with:
        image: distroless-k8s-test
        config: tests.yaml

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: template.tar
    #     path: ./output.tar
